### PR TITLE
Change styles of Actor and Monster sheet headers.

### PR DESCRIPTION
**Pull request by Airamhh**
Hello again!

I'm planning on styling a bit the sheets, starting for the Actor and Monster sheet, focusing now in the headers and making it more readeable for the players, I hope you like them.

The most visually things I changed are the inputs without borders and the health and mp bars are now in the right part of the sheet with the health inside the bars.

I changed the borders of the tabs as well giving it an effect of being in a tab.

I reordered some attributes and information as I thought they were more important to show and the order of them.

I tried to mainting the starting styles of the system, so feel free to change or discard anything you don't like! (css classes, naming, colors, structure...)

Here's an screenshot of the new styles!

image

### CODE REVIEW

**Comment by jeannjeann** [comment]
Good design, in my opinion.
But I would ask the community I know which is preferable compared to the current design. Can I decide whether to merge them or not based on the results of that?
Then, as a minor preference, I would prefer the header to be a little lower in height. This is based on the idea of having as little of the character sheet scrolling as possible, even on smaller resolution displays.
Would it be possible to make the entire header smaller by making the actor images and resource bar a bit smaller and reducing the header line spacing?
One more thing, I think the Adventurer Level and Monster Level are important and I prefer to make them stand out.
Here is the text translated by DeepL.

**Comment by Airamhh** [comment]
Thanks!

Sure thing, I know styles are very subjective so you can change and reorder all you need.

And yeah, I will adjust more the header height and stand out the Adventure and Monster level, whenever I have it done I'll let you know!

**Comment by Airamhh** [comment]
Hello, hello!

I adjusted a bit the styles again, now making the header a little bit smaller, it could be even more smaller if we compress more data.

**Comment by jeannjeann** [comment]
Merged. I will release it with a few modifications.
Thanks.

**Pull request merged**
